### PR TITLE
Stable : multiple face, face checkpoints, gender detection, face blending, face extraction, face comparison

### PR DESCRIPTION
**Pull request by glucauze**
Had to restart for a clean PR (and less mess in git logs). This is the continuation of https://github.com/s0md3v/sd-webui-roop/pull/118

roop0 1

This PR brings the following changes :

+ Roop Tab with tools
+ Roop settings in sd settings
+ allow reuse of faces via checkpoints (~ 2kb). Checkpoints can be built in the FaceTools tab. Checkpoints have precedence over reference img (reference source image is discarded but not the batch source images).
+ gender detection of faces (face numbers only concern gender, can be disabled)
+ face combination (blending) sources, references and checkpoints. Blending is activated by default. Allow the use of multiple version of a face to improve the result. Blending is also performed when building face checkpoint. This is done via the batch source image option when blend is activated.
+ notion of face unit as for controlNet. For the moment, 3 default units (this is an option in sd, up to 10)
+ keep original images before swap (option)
+ several versions of the same face can be used for replacement: several images generated if blend is not activated, mixed faces otherwise. This is done via the batch source image option.
+ face similarity and filtering (against reference and/or against source). This is configured via the 2 sliders (min sim and min ref sim). Ref is the checkpoint or the ref image.
+ face comparison in tools
+ face extraction (using upscaling or not) in tools
+ post inpainting : allow to apply image to image to faces
+ ldsr upscaled inswapper (may help get better results). Use LDSR+sharpness+color correction. Option in sd settings.
+ api example (not retested)

Performance improvement : don't use temp files anymore (useless), process the source face only once, checkpoints are also faster since no analysis is required. There is also a fix for install that should be better (except for opencv, i dunno why)

This is based on a slightly older version of the faceswap plugin (which is no longer public) that evolved separately. I have tried my best to reintegrate the roop changes.  

This should be stable enough to try and merge ?

TODO : a cleaner API.

### CODE REVIEW

**Comment by dhwz** [comment]
Last version does always say "Roop - INFO - Restore face with CodeFormer" even if it's not enabled?

**Comment by glucauze** [comment]
@dhwz That's strange, i just tested and i don't have that behaviour.

I made some minor changes since your last version. I added options for the upscaled inswapper in sd settings. But I don't think I've modified anything related to the activation of the face restorer.

**Comment by dhwz** [comment]
Hm just cloned your repo again but it's always happening for me.

**Comment by glucauze** [comment]
Yes you are right, i think the last commit should fix this. Note that upscale will work if any face is enabled (whether or not swapping was possible)

**Comment by gunser12** [comment]
hi, i have something troubles :D SD Vladmandic, Python 3.10.6 
image

**Comment by glucauze** [comment]
You cannot use the png file as a checkpoint. You should use the pkl file (Face.pkl not Face.pkl.png in your example). Models should be discovered if you click refresh and then select the pkl

**Comment by mesax1** [comment]
Hey, in my case the last version is always applying Blend Faces. It is not outputting one image per each image in the Batch Source Images . It only outputs one image, regardless of having Blend Faces 'activated' or 'deactivated'.

**Comment by glucauze** [comment]
@mesax1 You're absolutely right about the blend. I broke the thing trying to simplify it. It's even worse than that, only the first image will be taken into account if blend isn't activated. It's going to take me a bit of thinking to solve the problem simply. I hope it's not too critical at the moment.


The 'original' image is captured in the process batch method, so it doesn't benefit from any post-processing. However, on my side, if post-processing such as restore face or hiresfix are not activated, I get the same image as the one generated without swap. It would be a bit of a pain to go through all the post-processing again (not impossible, but a pain). Is this really a sticking point?

**Comment by gunser12** [comment]
and another error (vladmandic), but this error is not on 1111
image

**Comment by acsaga** [comment]
Could you incorporate roop into the "extras" tab or include a "batch process" option within the roop tools?
This would allow us to apply roop to the images (single or batch) directly.
It would be incredibly beneficial.

**Comment by glucauze** [comment]
Ok I made some deep changes and reorganized the code:
+ I corrected a problem with blending that wasn't working properly and with comparison. Comparison is disabled by default (for performance)
+ Added the possibility of configuring default options for post-processing (requires restart).
+ Added weight option for codeformer.
+ Added options for upscale inswapper including face_restore, and options on how the blending mechanism works (fthresh and erosion). The most interesting is erosion, since it reduces the size of the mask around the face (and avoids certain artifacts). However, if the value is set too high, the replaced face will disappear.

I hope I haven't introduced any bugs. The number of changes I've made doesn't always allow me to test everything exhaustively.

**Comment by sra-tatata** [comment]
2023-07-14 17:28:02,046 - Roop - INFO - blend all faces together0:00,  6.33it/s]
*** Error running postprocess: /home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui/modules/scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 370, in postprocess
        swapped_images = self.process_image_unit(image=img, unit=unit, info=info, upscaled_swapper=self.upscaled_swapper_in_generated)
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 298, in process_image_unit
        src_faces = [unit.blended_faces]
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 170, in blended_faces
        self._blended_faces = swapper.blend_faces(self.faces)
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 156, in faces
        self._faces = [self.reference_face] if self.reference_face is not None else []
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 121, in reference_face
        with open(self.source_face, "rb") as file:
    FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by sra-tatata** [comment]
2023-07-14 17:33:45,519 - Roop - INFO - blend all faces together0:00,  6.32it/s]
*** Error running postprocess: /home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui/modules/scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 370, in postprocess
        swapped_images = self.process_image_unit(image=img, unit=unit, info=info, upscaled_swapper=self.upscaled_swapper_in_generated)
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 298, in process_image_unit
        src_faces = [unit.blended_faces]
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 170, in blended_faces
        self._blended_faces = swapper.blend_faces(self.faces)
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 156, in faces
        self._faces = [self.reference_face] if self.reference_face is not None else []
      File "/home/user/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 121, in reference_face
        with open(self.source_face, "rb") as file:
    FileNotFoundError: [Errno 2] No such file or directory: ''

---
Total progress: 100%|███████████████████████████| 20/20 [00:03<00:00,  5.42it/s]
Total progress: 100%|███████████████████████████| 20/20 [00:03<00:00,  6.32it/s]
Zrzut ekranu z 2023-07-14 17-34-05
Zrzut ekranu z 2023-07-14 09-13-28

**Comment by glucauze** [comment]
@sra-tatata select None in face checkpoints to see if it solves it

**Comment by sra-tatata** [comment]
Yes, 
2023-07-14 17:39:40,886 - Roop - INFO - blend all faces together0:00,  7.12it/s]
set det-size: (640, 640)
set det-size: (320, 320)
/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
2023-07-14 17:39:41,589 - Roop - INFO - Process face 0
2023-07-14 17:39:41,589 - Roop - INFO - Try to use model : /home/user/stable-diffusion-webui/models/roop/inswapper_128.onnx
2023-07-14 17:39:41,589 - Roop - INFO - Source Gender 1
set det-size: (640, 640)
2023-07-14 17:39:41,984 - Roop - INFO - Target faces count : 1
2023-07-14 17:39:41,984 - Roop - INFO - swap face 0
fthresh 10
2023-07-14 17:39:42,411 - Roop - INFO - 1 images swapped
2023-07-14 17:39:42,411 - Roop - INFO - unit 1> processed
2023-07-14 17:39:42,411 - Roop - INFO - Restore face with CodeFormer
2023-07-14 17:39:42,721 - Roop - INFO - Add swp image to processed
Zrzut ekranu z 2023-07-14 17-43-28


but the picture is blurry, especially the plaid shirt

00042-3946734940-swapped

**Comment by glucauze** [comment]
As for that, it's been discussed many times (insightface gives shitty results). The best you can do is upscale and use a face restorer. Try the upscaled_inswapper options in settings with LDSR, for example. Otherwise there's nothing that can be done.

**Comment by glucauze** [comment]
Should be fixed.

I also made a changed to where the analyzer model is stored. It should be automatically download in models/roop/analyzers.

This will cause the model to be download once again.

**Comment by glucauze** [comment]
@dhwz No, strongly against it

**Comment by arhgap11b** [comment]
How to install update? Can't find info. I have reinstalled roop, but i still have 0.0.2 version

**Comment by sra-tatata** [comment]
> How to install update? Can't find info. I have reinstalled roop, but i still have 0.0.2 version

Go to stable-diffusion-webui/extensions
Remove sd-webui-roop folder
Run SD and install from url https://github.com/glucauze/sd-webui-roop.git
in Extensions->Install from URL->URL for extension's git repository

**Comment by SwatMessiah** [comment]
current version bugs returned:

 - a1111 settings / roop / keep original image before swapping (makes no difference, always saves the original and swapped image)
 - swapped image has no generation parameters stored

but still ty for your work :) 👍

**Comment by glucauze** [comment]
@SwatMessiah :  

1. Actually keep original should be named "Show Original". If saving is disabled both will not be saved. Could be fixed. 
2. Yes i know :/

Will try to fix this if i have time.

**Comment by glucauze** [comment]
@SwatMessiah :

    Actually keep original should be named "Show Original". If saving is disabled both will not be saved. Could be fixed.
    Yes i know :/

Will try to fix this if i have time.

**Comment by glucauze** [comment]
@SwatMessiah Last version should fix it. Now only saves when keep is enabled and info should also be saved to png

@gunser12 did install vladmandic. The problem was that a method did not exist in vlad but in a1111. It seems to be fixed, but I can't guarantee that I'll maintain consistency for both.

**Comment by glucauze** [comment]
The latest version should correct inpainting, especially when the "only mask" option is activated. The only drawback in the latter case is that blurring is not yet really taken into account. It should also solves the inpainting problem in vladmandic.

The grid should also be set, although the appearance of the grid for swapped images will not be the same as for the original images (since there may be more images).

**Comment by SwatMessiah** [comment]
@glucauze just to let you know - found a small save bug :)
maybe just an if roop enabled check missing

Roop face disabled (Bug):
	- "Keep original" unchecked -> no image is saved
	- "Keep original" checked -> default image gets saved


Roop face enabled (correct working):
	- "keep original" unchecked -> both are saved
	- "keep original" checked -> only swapped is saved

**Comment by glucauze** [comment]
@s0md3v I think the last version is stable enough to be merged. Is there a change for a merge for the current version ?

**Comment by glucauze** [comment]
The latest version is supposed to solve a problem with multiface swapping, where several images are generated instead of just one.

I've also started work on a more advanced version of the api

I'll see about a batch function later.

The extension is getting quite complex and I need feedback to identify bugs. 

I'm starting to worry about the fact that the official extension isn't being maintained, which leaves room for nsfw forks that I find dangerous.

**Comment by SwatMessiah** [comment]
@glucauze your doing great work!
maybe you can add this as a seperate extension for a1111 like "roop-extended" (a1111 - index.json request?)
if this gets not merged into the default one.

nfsw checkbox in the settings would be fine :), i support - it is your own decision if you wana use it for nsfw

**Comment by glucauze** [comment]
@SwatMessiah I totally get why people wants it as an option. But it would make it too easy to bypass. I am not against nsfw in general on sd. I am against swapping the face of a real person into nsfw content which is really different. If it were possible to check that the faces were synthetic faces (which is currently not reliably possible) before making the swap, I would have no problem with this. Making it easy for everyone seems ethically risky. In any case, I wouldn't take this responsibility on a personal level. I wouldn't want to feel responsible for someone being harassed with this tool.

The last version introduces a first version of the api. It works on my tests. The aim is to have something simpler and better typed than the basic api. The only function currently available allows you to change the faces in an image, which is the most common case.

The example/api directory contains some utility functions with pydantic and an example. It requires to have pydantic and requests.

**Comment by glucauze** [comment]
@acsaga Last commit add batch in tools.

Last version add the following features : 
+ add inpainting model selection => allow to select a different model for face inpainting
+ add source faces selection => allow to select the reference face if multiple face are present in reference image
+ add select by size => sort faces by size from larger to smaller
+ add batch option => allow to process images without txt2img or i2i in tabs
+ add segmentation mask for upscaled swapper (based on codeformer implementation) : avoid square mask and prevent degradation of non-face parts of the image.

Some depends on upscaled swapper which can be checked in sd settings. Got good results with 003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN instead of LDSR for upscaled inswapper. It's very fast and results are quite the same depending on the type of images.

Known bug : error messages can be improved, api does not use upscaler.

**Comment by glucauze** [comment]
I close this PR and switch to the following project: https://glucauze.github.io/sd-webui-faceswaplab/doc/

The original project will be deleted

**Pull request closed without merging**
