### PR TITLE
support api

### PR DESCRIPTION
**Pull request by SpenserCai**
I have implemented support for the standard API interface for sd-webui-roop.
#199 #82 
截图 2023-08-20 22-38-41
截图 2023-08-20 22-39-16

### CODE REVIEW

**Comment by StuJLans** [comment]
This looks awesome

**Comment by SpenserCai** [comment]
> This looks awesome, is there a way to do like a text 2 image prompt and adjust the other settings with this?

if in api use,you can call t2i first then use output to call roop/image

**Comment by chaoqunxie** [comment]
does not work ,gen image  is same than before

**Comment by YuFong** [comment]
> does not work ,gen image is same than before

same issue

**Comment by YuFong** [comment]
> > does not work ,gen image is same than before
> 
> same issue

catch the reason!
image
the model name get by function get_full_model return None on windows PC

**Pull request merged**
