### PR TITLE
major change : multiple face, face checkpoints, gender detection, face blending, face extraction, face comparison

### PR DESCRIPTION
**Pull request by glucauze**
This is a first version of an important change:

+ allow reuse of faces via checkpoints (~ 2kb). Checkpoints can be built in the FaceTools tab. Checkpoints have precedence over reference img (reference source image is discarded but not the batch source images).
+ gender detection of faces (face numbers only concern gender, can be disabled)
+ face combination (blending) sources, references and checkpoints. Blending is activated by default. Allow the use of multiple version of a face to improve the result. Blending is also performed when building face checkpoint. This is done via the batch source image option when blend is activated.
+ notion of face unit as for controlNet. For the moment, 3 possible units (this is hard coded but could be an option)
+ several versions of the same face can be used for replacement: several images generated if blend is not activated, mixed faces otherwise. This is done via the batch source image option.
+ face similarity and filtering (against reference and/or against source). This is configured via the 2 sliders (min sim and min ref sim). Ref is the checkpoint or the ref image.
+ face comparison in tools
+ face extraction (using upscaling or not)

Performance improvement : don't use temp files anymore (useless), process the source face only once, checkpoints are also faster since no analysis is required.

This is based on a slightly older version of the faceswap plugin (which is no longer public) that evolved separately. I have tried my best to reintegrate the roop changes. I haven't yet reimplemented the API part. It works for me, but there may still be bugs. Think of it as a proposal of what roop could be.

TODO : save image, reactivate API, cleanup the mess in the interface (the parsing of arguments is tricky).

### CODE REVIEW

**Comment by SwatMessiah** [comment]
for version - major change #118 sha - 9c6baf11b1131c6161e33f5b46e68db762543fe6

i testet your version, very nice changes!

one problem i have is its not autosaving the "restored" image (windows 11). maybe you can add a path in the roop-settings tab or a checkbox "save restored image"

great work ;)

**Comment by SwatMessiah** [comment]
i also found after the tex2img with Highres fix - the face get not swapped and in the a1111 ui there is a empty preview after complete

**Comment by glucauze** [comment]
should be fixed in the last commit. Also added an API example (API is not really easy to use right now) in example directory. API should work.
Note that hires.fix will happen before swapping in the current implementation.

**Comment by SwatMessiah** [comment]
let you know if i found an error, but works very nice - love the idea of the "face model" works great!

maybe a QoL feature: 
 - use the same image name and just add swapped?
 - add gen info from original image

keep up the good work! 👍 :)

**Comment by SwatMessiah** [comment]
fix for Batch-size and Batch-count:

`if p.batch_size > 1:`
changed to
`if p.batch_size > 1 or p.batch_count > 1:`

**Comment by glucauze** [comment]
Hey, thanks for the feedback. Didn't see your last message before committing. I have a solution based on your first suggestion (it don't breaks the batch).

I added some documentation inside the extension
I renamed upscaler to enhancements.

There is now an option to perform inpainting of each faces before upscaling. This is useful to modify the faces after the swapping occur.

**Comment by SwatMessiah** [comment]
> 

Hey, no problem :) thanks for your work. realy like your "roop" version

i removed it because it was a failed code ;)
thought:
if p.batch_size > 1 or p.batch_count > 1: 
would work but after restart it throws an error ('StableDiffusionProcessingTxt2Img' object has no attribute 'batch_count')

**Comment by dhwz** [comment]
@glucauze 
Two complaints :-)
1. swapped Images are stored even if "Always save all generated images" is disabled
2. Image is stored as "swapped-0000-1389764686-[prompt_spaces]" in stead of storing it to the original filename e.g. 02709-1389764686-woman, naked, nsfw.jpg, why is isn't it copied to the final filename I don't want the duplicated one (without swap).

**Comment by glucauze** [comment]
@SwatMessiah should be fixed. This was due to the fact that when inpainting tried to save the image (useless).

@dhwz : 
1. should be fixed
2. a bit of refactoring is needed for that, will wait. It's anoying but it doesn't hinder use
3. Renamed FaceTools to Roop. Removed from accordion. There was no tab at first and I left it at that.
4. I'll look at adding it to the settings panel if I have time. For the moment, it allows you to easily activate/deactivate the saving of images before the swap. And it would make it possible to quickly change models in the unlikely event that a new one becomes available.

**Comment by dhwz** [comment]
@glucauze Probably a bug, the Enhancements section is also displayed on the "Face Tools (now Roop)" menu?

**Comment by glucauze** [comment]
It's not a bug, it allows to play with it during extraction

**Comment by SwatMessiah** [comment]
just an idea - in the enhancement section you could also add something like add ISO noise with a strength slider appled as last step

**Comment by glucauze** [comment]
@SwatMessiah  Could you elaborate a bit more on the usefulness of this?

If we add noise (which img2img must already have done), won't that mean deviating a lot from the original model?

Apart from that,  does the extension work normally?

**Comment by SwatMessiah** [comment]
@glucauze it was just an idea
when you add some fine "iso noise / film grain / Gaussian noise" over the image it looks for the eye more "realistic" because the skin is less smooth

**Comment by SwatMessiah** [comment]
@glucauze  here is my prototype.. what i mean ;) 
with the "hardcoded" settings it makes the image more real maybe you can put them as sliders
its not optimized but you can runn it python noisetest_05.py

    import os
    import numpy as np
    from PIL import Image, ImageChops

    # Folder paths
    source_folder = "source"
    output_folder = "output"

    # Create the source folder if it doesn't exist
    if not os.path.exists(source_folder):
        os.makedirs(source_folder)

    # Create the output folder if it doesn't exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Strength values for noise
    strength_values = [0.2, 0.5, 0.8] #[0.2, 0.5, 0.8]
    global_strength = 0.2 # Adjust the global noise strength (0-1)

    DebugOutputBool = True
    blendingMethodArray = ["Alpha Blending", "Overlay Blending", "Multi-Layer Blending"]
    blendingMethod = 2  # Index of the blendingMethodArray
    finalBlendingMethod = 2

    noiseBlackAndWhite = True # Change the noise to black and white

    # List to hold the noisy images for blending
    noisy_images = []

    def add_noise(image_path, strength, returnBlackAndWhite=False):
        # Load the image
        image = Image.open(image_path).convert("RGBA")

        # Convert the image to a NumPy array
        image_array = np.array(image)

        # Define parameters for noise generation
        iso_mean = 0
        iso_stddev = 25
        gaussian_mean = 0
        gaussian_stddev = 10
        film_grain_strength = 0.2

        # Generate ISO noise with the same shape as the image
        iso_noise = np.random.normal(iso_mean, iso_stddev, image_array.shape[:-1]).astype(np.uint8)
        scaled_iso_noise = (strength * iso_noise).astype(np.uint8)

        # Generate Gaussian noise with the same shape as the image
        gaussian_noise = np.random.normal(gaussian_mean, gaussian_stddev, image_array.shape[:-1]).astype(np.uint8)
        scaled_gaussian_noise = (strength * gaussian_noise).astype(np.uint8)

        # Generate film grain
        film_grain = np.random.normal(0, film_grain_strength, image_array.shape[:-1]).astype(np.uint8)
        scaled_film_grain = (strength * film_grain).astype(np.uint8)

        # Create an RGBA array for the noise
        noise_array = np.dstack([scaled_iso_noise, scaled_gaussian_noise, scaled_film_grain, np.full_like(scaled_iso_noise, 255)])

        # Create a noisy image by overlaying the noise with alpha blending
        noisy_array = np.where(noise_array > 0, noise_array, 0)
        noisy_image_array = np.clip(image_array + noisy_array, 0, 255).astype(np.uint8)

        # Create a new Image object from the noisy array
        noisy_image = Image.fromarray(noisy_image_array, "RGBA")

        if returnBlackAndWhite:
            # Convert noisy image to black and white
            noisy_image = noisy_image.convert("L")
            
            # back to rgba
            noisy_image = noisy_image.convert("RGBA")
            
            # Resize the black and white image to match the size of the original image
            noisy_image = noisy_image.resize(image.size)

        return noisy_image


    # Apply noise for each strength value to images in the source folder
    for filename in os.listdir(source_folder):
        if filename.endswith(".jpg") or filename.endswith(".png"):
            image_path = os.path.join(source_folder, filename)

            # Generate noisy images for different strength values
            for i, strength in enumerate(strength_values):
                noisy_image = add_noise(image_path, strength, noiseBlackAndWhite)
                noisy_images.append(noisy_image)

                if DebugOutputBool:
                    # Save individual noisy images
                    noisy_image_path = os.path.join(output_folder, f"{filename[:-4]}_noisy_{i}.png")
                    noisy_image.save(noisy_image_path)
                    print(f"Noisy image saved as {noisy_image_path}")

            # Create a composite image by overlaying the noisy images
            composite_image = Image.new("RGBA", noisy_images[0].size)

            for i, noisy_image in enumerate(noisy_images):
                #alpha = int(255 * strength_values[i])
                overlay_image = Image.new("RGBA", composite_image.size, (0, 0, 0, int(255 * 0.5)))

                if blendingMethod == 0:
                    composite_image = Image.alpha_composite(composite_image, noisy_image)
                elif blendingMethod == 1:
                    composite_image = ImageChops.overlay(composite_image, noisy_image)
                elif blendingMethod == 2:
                    composite_image = Image.blend(composite_image, noisy_image, 0.5)
                    
            composite_image_path = os.path.join(output_folder, f"{filename[:-4]}_composite_image_merge.png")
            composite_image.save(composite_image_path)

            # Overlay the composite image on the original image using global_strength
            original_image = Image.open(image_path).convert("RGBA")

            # Adjust the strength of the blending
            blended_alpha = ImageChops.multiply(composite_image.split()[-1], Image.new('L', original_image.size, int(255 * global_strength)))

            # Create the overlay image with the adjusted alpha channel
            overlay_image = Image.new("RGBA", original_image.size)
            overlay_image.putalpha(blended_alpha)

            # Subtract the composite image from the original image
            blended_image = ImageChops.subtract(original_image, composite_image)

            if finalBlendingMethod == 0:
                blended_image = Image.alpha_composite(original_image, ImageChops.multiply(composite_image, overlay_image))
            elif finalBlendingMethod == 1:
                blended_image = ImageChops.overlay(original_image, ImageChops.multiply(composite_image, overlay_image))
            elif finalBlendingMethod == 2:
                blended_image = Image.blend(original_image, composite_image, global_strength)

            # Save the blended image
            blended_image_path = os.path.join(output_folder, f"{filename[:-4]}_blended_{blendingMethod}.png")
            blended_image.save(blended_image_path)
            print(f"Blended image saved as {blended_image_path}")

            if DebugOutputBool:
                # Create a grid image with original image on the left and blended image on the right
                grid_image = Image.new("RGB", (original_image.width * 2, original_image.height))
                grid_image.paste(original_image, (0, 0))
                grid_image.paste(blended_image, (original_image.width, 0))

                # Save the grid image
                grid_image_path = os.path.join(output_folder, f"{filename[:-4]}_grid_{blendingMethod}.png")
                grid_image.save(grid_image_path)
                print(f"Grid image saved as {grid_image_path}")

**Comment by glucauze** [comment]
Hey thanks for your work. I did try it a bit, but i think the noise was too heavy and i was not completly convinced. I will give it another try latter and see if it's possible to integrate. 

I added an custom inswapper class that use ldsr to upscale the 128*128 swapped face by a 4 factor and a add a bit of sharpness. This is done only on faces. It is disabled by default but can be tested by enabling upscaled swapper in sd settings (roop). It does not requires restart. It's not perfect but it tends to give more realistic results as far as i have seen. It takes a bit longer to process (of course).

**Comment by SwatMessiah** [comment]
i would also keep the noise low like remap a slider form 0-1 to the noise value (0-0.3)
but it was just an idea ;) feel free to use it or not its no problem

**Comment by Fenrir200678** [comment]
Just checked this fork out a couple of hours ago and played around with it. Really nice changes!  Only thing I couldn't get to work is using this with regular A1111 inpainting. So I want the faceswap only in my masked area, but it's always doing a full swap no matter what and where I mask. This worked fine in the original version. 

I know I can inpaint via Post Inpainting in Enhancement tab, but also there is no way to mask out an area. 

Am I missing something or is that just not (yet?) implemented?

**Comment by glucauze** [comment]
No, you're probably right. To allow an option to view the original images, I had to migrate the moment the processing was done. It has to be said that a1111's documentation on extensions isn't always very clear to me.

As a side effect, this has probably changed the way impainting is done. I'll have to have a look.

**Comment by glucauze** [comment]
@Fenrir200678 the problem should be fixed.  I've changed the way the processing is carried out back to the method I used previously.

I've also solved the file naming problem as far as i have seen.

**Comment by Fenrir200678** [comment]
Seems to work fine after a few quick tests. Thank you!

**Comment by glucauze** [comment]
Had to close and restart the code base for cleaner git project. I resubmitted a pr. You will likely have to remove/reinstall to test.

**Pull request closed without merging**
